version: "3"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        image: api
        ports:
            - "8000:5000"
        expose:
            - "8000"
        networks:
            - { NETWORK }
networks:
    { NETWORK }:
        external: true
