FROM python:3

COPY requirements.txt /
ADD requirements.txt /

RUN pip install -r requirements.txt
RUN pip install gunicorn

COPY . .

ENV FLASK_APP init.py
# RUN flask db init
# RUN flask db migrate
# RUN flask db upgrade


# Binding to a container in the same network, you would use the internal port
# rather than the external port. Which is the common case
EXPOSE 8000
EXPOSE 5000

CMD ["gunicorn", "-c", "gunicorn.conf", "wsgi:application", "--log-level=info"]
