# Dockerfile-flask
# We simply inherit the Python 3 image. This image does
# not particularly care what OS runs underneath
FROM ubuntu:18.04
FROM python:3

LABEL maintainer="Keith Byrne <keithmbyrne@gmail.com>"

RUN apt-get update -y
RUN apt-get install -y python3 python3-dev python3-pip nginx uwsgi-plugin-python
RUN pip3 install uwsgi
RUN python3 -m venv venv

COPY requirements.txt /

# Install Python dependencies
ADD requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt
RUN pip3 install uwsgi

COPY . /app
WORKDIR ./app

# Set an environment variable with the directory
# where we'll be running the app
ENV APP /app

# Expose the port uWSGI will listen on
EXPOSE 5050

# Ensure default is actually removed. Seems to be issues with this
RUN rm -v /etc/nginx/sites-enabled/default

# Ensure that the default NGINX config is the applications config
COPY ./deploy/nginx.conf /etc/nginx/sites-enabled/bns
RUN nginx -t
RUN ls -l /etc/nginx/sites-enabled
RUN cat /etc/nginx/sites-enabled/bns

CMD service nginx restart && uwsgi -s /tmp/uwsgi.sock --chmod-socket=666 --manage-script-name --mount /=wsgi:application

# CMD [ "uwsgi", "--ini", "app.ini" ]
